version: "3.8"

services:
  database:
    image: 17.3-alpine3.21
    container_name: database_crypto
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Kiloma123@}
      POSTGRES_DB: ${DB_NAME:-Crypto}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"

  caching:
    image: redis:7.4-alpine
    container_name: caching_crypto
    command: redis-server --port 6379 --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    name: ${SERVICE_NAME:-crypto-dashboard}_postgres_data
  redis_data:
    name: ${SERVICE_NAME:-crypto-dashboard}_redis_data

networks:
  crypto_network:
    name: ${SERVICE_NAME:-crypto-dashboard}_network
    driver: bridge
